FROM loupe-base:latest

RUN apt update && apt install -y libncurses5-dev wrk

# erlang
RUN wget https://github.com/erlang/otp/releases/download/OTP-25.2/otp_src_25.2.tar.gz -O /root/erlang.tar.gz
RUN cd /root && tar xf erlang.tar.gz
RUN cd /root/otp_src_25.2 && ./configure && make -j install

# yaws
RUN apt-get build-dep -y yaws
RUN wget https://github.com/erlyaws/yaws/archive/refs/tags/yaws-2.1.1.tar.gz -O /root/yaws.tar.gz
RUN cd /root && tar xf yaws.tar.gz
RUN cd /root/yaws-yaws-2.1.1 && autoreconf -fi && ./configure && make install -j

COPY dockerfile_data/yaws-test.sh /root/yaws-test.sh
RUN chmod +x /root/yaws-test.sh

CMD /root/explore.py --output-csv --disable-static \
                     --timeout 10 -t /root/yaws-test.sh \
                     -b /usr/local/bin/erl -- +K true -pa /usr/local/lib/yaws/ebin -run yaws -yaws encoding latin1
